# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hi! I'm Zoya!
email:            cutezoe1996@gmail.com
tagline:          'Stronger|Better|Faster'
description:      "Machine Learning Enthusiast| Student|Full Stack Developer| Coder|Massive Arsenal Fan|"
url:              https://zeddmaxx.github.io/
baseurl:
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Zoya Khan'
  url:            https://twitter.com/zeddmaxx

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

github:
  repo:           https://github.com/zeddmaxx/zeddmaxx.github.io

google_analytics: UA-131116358-1


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
